#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use DLR\DedupeCommand;
use DLR\LinkCommand;
use DLR\RemapCommand;

ini_set('memory_limit','-1');
set_time_limit(0);

require_once 'vendor/autoload.php';
require_once 'config/database.php';

$app = new Application('MySQL Database Deduplication and Remap Tool', '1.0');

$app->add(new DedupeCommand);
$app->add(new LinkCommand);
$app->add(new RemapCommand);

$app->run();