#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use DRT\DedupeCommand;
use DRT\RemapCommand;

ini_set('memory_limit','-1');
set_time_limit(0);

require_once 'vendor/autoload.php';
require_once 'config/database.php';

$app = new Application('Database Deduplication and Remap Tool', '1.0');

$app->add(new DedupeCommand);
$app->add(new RemapCommand);

$app->run();