#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use DRT\DedupeCommand;
use DRT\RemapCommand;

require_once 'vendor/autoload.php';

$app = new Application('Dedupe and Remap Tool (DRT)', '1.0');

$app->add(new DedupeCommand);
$app->add(new RemapCommand);

$app->run();

// use Illuminate\Database\Capsule\Manager as Capsule;
//     Capsule::schema()->create('orders', function($table) {
// });