#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputArgument;
use DRT\Dedupe;

require_once 'vendor/autoload.php';
require_once 'config/database.php';

$app = new Application('Dedupe and Remap Tool (DRT)', '1.0');

$app->register('dedupe')
    ->setDescription('De-duplicate a table')
    ->addArgument('table', InputArgument::REQUIRED, 'The table to be deduped')
    ->addArgument('columns', InputArgument::REQUIRED, 'Colon seperated rows that define the uniqueness of a row')
    ->setCode(function(InputInterface $input, OutputInterface $output) use ($db) {
       
        $table = $input->getArgument('table');
        $columns = explode(':', $input->getArgument('columns'));

        $drt = new Dedupe($db);
        $drt->dedupe($table, $columns);
    });

$app->run();


// $output->writeln('hello');

// use Illuminate\Database\Capsule\Manager as Capsule;
//     Capsule::schema()->create('orders', function($table) {
// });