#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use DRT\ExtractCommand;
use DRT\LinkCommand;
use DRT\RemapCommand;
use DRT\DeleteCommand;

 ini_set('memory_limit','-1');
 set_time_limit(0);

require_once 'vendor/autoload.php';
require_once 'config/database.php';

$app = new Application('Database Deduplication and Remap Tool (Ellard)', '1.0');

$app->add(new ExtractCommand);
$app->add(new LinkCommand);
$app->add(new RemapCommand);
$app->add(new DeleteCommand);

$app->run();